Repository MetaMask/github-tools, pull requests merged in 2025-04, with the labels that each got.

#57 feat: GH action to remind developers to add release notes in CHANGELOG.md
  .github/workflows/changelog-check.yml
  package.json
  src/changelog-check.ts
  src/scripts/count-references-to-contributor-docs/cli.ts
  yarn.lock
Labels: team-wallet-framework

#49 feat(ci): Add changed lines check
  .github/workflows/pr-line-check.yml
Labels: team-extension-platform

#58 INFRA-2406: Shared RCA workflow
  .github/workflows/post-gh-rca.yml
Labels: team-dev-ops

#61 feat: improve changelog check workflow
  .github/workflows/changelog-check.yml
  src/changelog-check.ts
Labels: team-wallet-framework

#62 fix(changelog-check): use correct reference in workflow checkout
  .github/workflows/changelog-check.yml
Labels: team-wallet-framework
