Repository MetaMask/github-tools, pull requests merged in 2025-05, with the labels that each got.

#63 chore(changelog-check): add action-sha input for correct repository checkout
  .github/workflows/changelog-check.yml
Labels: team-wallet-framework

#68 chore(changelog-check): exclude private packages from changelog check
  src/changelog-check.ts
Labels: team-wallet-framework

#67 feat(INFRA-2510): add team and regression labels
  .github/workflows/post-gh-rca.yml
Labels: team-dev-ops

#66 chore: adapt common stale bot config
  .github/workflows/stale-issue-pr.yml
Labels: team-qa

#70 chore: update stale bot to process only issues with needs-information, needs-reproduction label
  .github/workflows/stale-issue-pr.yml
Labels: team-qa

#72 additional logging on generation of commits.csv
  .github/scripts/generate-rc-commits.mjs
Labels: team-dev-ops
