Repository MetaMask/github-tools, pull requests merged in 2025-09, with the labels that each got.

#115 chore(master): rename master branch into stable
  .github/scripts/get-release-timelines.sh
  .github/workflows/stable-sync.yml
Labels: team-extension-platform

#116 INFRA-2849: Made extension work with release/x.y.z branch syntax
  .github/scripts/create-platform-release-pr.sh
Labels: team-dev-ops

#117 ci: small fixes
  .github/scripts/create-flaky-test-report.mjs
  .github/scripts/post-merge-validation-tracker.mjs
Labels: team-qa

#124 ci: default to 1 day for lookback PRs for post validation
  .github/workflows/post-merge-validation.yml
Labels: team-qa

#125 chore(branches): rename Version-vx.y.z branches into release/x.y.z
  .github/scripts/create-platform-release-pr.sh
  .github/scripts/tests/test-create-platform-release-pr-full.sh
  .github/scripts/tests/test-create-platform-release-pr-functions.sh
Labels: team-extension-platform

#133 ci: update auto-changelog to v5.1.0
  .github/scripts/create-platform-release-pr.sh
  .github/scripts/tests/test-create-platform-release-pr-full.sh
  .github/workflows/stable-sync.yml
  package.json
  src/changelog-check.ts
  yarn.lock
Labels: team-extension-platform
