Repository MetaMask/github-tools, pull requests merged in 2025-03, with the labels that each got.

#42 ci: new checkout-and-setup to support prep-deps and caching
  .github/actionlint.yml
  .github/actions/checkout-and-setup/action.yml
  .github/actions/setup-environment/action.yml
  .github/workflows/build-lint-test.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/lint-workflows.yml
  .github/workflows/main.yml
  .github/workflows/test-checkout-and-setup.yml
Labels: team-extension-platform

#48 ci: followup to checkout-and-setup with new SHA
  .github/workflows/test-checkout-and-setup.yml
Labels: team-extension-platform

#50 feat(projects): Add issues and PRs to github projects by team
  .github/workflows/add-item-to-project.yml
Labels: team-wallet-framework

#52 fix(actions): Remove GH Token from secrets it gets it automatically
  .github/workflows/add-item-to-project.yml
Labels: team-wallet-framework, team-extension-platform

#53 fix: add proper secrets definition to `add item to project` workflow
  .github/workflows/add-item-to-project.yml
Labels: team-wallet-framework
