Repository MetaMask/github-tools, pull requests merged in 2025-08, with the labels that each got.

#96 ci: adapt PR size job to add sizes label
  .github/workflows/pr-line-check.yml
Labels: team-qa

#102 fix(checkout branch): description was not correct
  .github/workflows/create-release-pr.yml
Labels: team-extension-platform

#108 INFRA-2867-Fix workflow inputs to allow branch name
  .github/scripts/create-platform-release-pr.sh
  .github/scripts/generate-rc-commits.mjs
  .github/workflows/create-release-pr.yml
Labels: team-dev-ops

#112 INFRA-2867: Skip version bump PR creation if already exists, commit in main
  .github/scripts/create-platform-release-pr.sh
Labels: team-dev-ops
